### ISSUE TITLE
al_Zeroconf_OSX.mm does not compile with GCC 4.9

### ISSUE THREAD

**Issue by DrewRWx** [AlloSphere-Research-Group/AlloSystem#29]
On Mavericks and GCC 4.9 is from MacPorts.

```
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm: In function '-[ClientDelegate search:]':
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:47:22: warning: class 'ClientDelegate' does not implement the 'NSNetServiceBrowserDelegate' protocol
     browser.delegate = self;
                      ^
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm: In function '-[ClientDelegate netServiceBrowser:didFindService:moreComing:]':
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:80:22: warning: class 'ClientDelegate' does not implement the 'NSNetServiceDelegate' protocol
     service.delegate = self;
                      ^
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm: In function '-[ClientDelegate resolvedService:]':
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:117:16: error: expected ';' before 'in'
  for(NSData *d in [service addresses]) {
                ^
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:117:16: error: 'in' was not declared in this scope
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:117:28: error: expected ']' before 'addresses'
  for(NSData *d in [service addresses]) {
                            ^
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:117:28: error: expected ';' before 'addresses'
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:117:28: error: 'addresses' was not declared in this scope
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:117:37: error: expected ')' before ']' token
  for(NSData *d in [service addresses]) {
                                     ^
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:117:37: error: expected primary-expression before ']' token
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm: In function '-[ServerDelegate initWithDomain:type:name:port:]':
/Users/dtemp/Development/MAT/AlloScraper/AlloSystem/allocore/src/protocol/al_Zeroconf_OSX.mm:150:23: warning: class 'ServerDelegate' does not implement the 'NSNetServiceDelegate' protocol
   netService.delegate = self;
```
